// Seed data for leads page - used when API is unavailable

export interface Property {
  id: string;
  address: string;
  city: string;
  state: string;
  zip: string;
  ownerName?: string;
  score?: number;
  dataSource: string;
  outreachStatus?: string;
  lastContactDate?: string;
  lastContactMethod?: string;
  sentiment?: string;
  nextFollowUpDate?: string;
  phoneNumbers?: string;
  emails?: string;
  contactNotes?: string;
  foreclosure: boolean;
  preForeclosure: boolean;
  taxDelinquent: boolean;
  vacant: boolean;
  createdAt: string;
  // Property details for underwriting
  bedrooms?: number;
  bathrooms?: number;
  squareFeet?: number;
  yearBuilt?: number;
  lotSize?: number;
  propertyType?: string;
  estimatedValue?: number;
  assessedValue?: number;
  lastSalePrice?: number;
  lastSaleDate?: string;
  county?: string;
  equityPercent?: number;
  mortgageBalance?: number;
}

export const seedProperties: Property[] = [
  {
    id: "prop-001",
    address: "1234 Oak Street",
    city: "Jacksonville",
    state: "FL",
    zip: "32205",
    county: "Duval",
    ownerName: "John Smith",
    score: 85,
    dataSource: "PropStream",
    outreachStatus: "contacted",
    lastContactDate: "2025-01-15",
    lastContactMethod: "sms",
    sentiment: "warm",
    nextFollowUpDate: "2025-01-28",
    phoneNumbers: "(904) 555-1234",
    emails: "john.smith@email.com",
    foreclosure: false,
    preForeclosure: true,
    taxDelinquent: false,
    vacant: false,
    createdAt: "2025-01-10",
    // Property details
    bedrooms: 3,
    bathrooms: 2,
    squareFeet: 1450,
    yearBuilt: 1965,
    lotSize: 0.18,
    propertyType: "Single Family",
    estimatedValue: 285000,
    assessedValue: 195000,
    lastSalePrice: 125000,
    lastSaleDate: "2015-03-22",
    equityPercent: 72,
    mortgageBalance: 80000,
  },
  {
    id: "prop-002",
    address: "567 Pine Avenue",
    city: "Orlando",
    state: "FL",
    zip: "32801",
    county: "Orange",
    ownerName: "Maria Garcia",
    score: 92,
    dataSource: "BatchLeads",
    outreachStatus: "hot",
    lastContactDate: "2025-01-20",
    lastContactMethod: "call",
    sentiment: "hot",
    nextFollowUpDate: "2025-01-25",
    phoneNumbers: "(407) 555-5678",
    emails: "mgarcia@gmail.com",
    foreclosure: false,
    preForeclosure: false,
    taxDelinquent: true,
    vacant: true,
    createdAt: "2025-01-05",
    // Property details
    bedrooms: 4,
    bathrooms: 2.5,
    squareFeet: 2100,
    yearBuilt: 1978,
    lotSize: 0.22,
    propertyType: "Single Family",
    estimatedValue: 325000,
    assessedValue: 245000,
    lastSalePrice: 175000,
    lastSaleDate: "2012-08-15",
    equityPercent: 85,
    mortgageBalance: 48000,
  },
  {
    id: "prop-003",
    address: "890 Maple Drive",
    city: "Tampa",
    state: "FL",
    zip: "33602",
    county: "Hillsborough",
    ownerName: "Robert Johnson",
    score: 67,
    dataSource: "ATTOM",
    outreachStatus: "new",
    phoneNumbers: "(813) 555-9012",
    foreclosure: true,
    preForeclosure: false,
    taxDelinquent: false,
    vacant: false,
    createdAt: "2025-01-18",
    // Property details
    bedrooms: 3,
    bathrooms: 1.5,
    squareFeet: 1200,
    yearBuilt: 1955,
    lotSize: 0.15,
    propertyType: "Single Family",
    estimatedValue: 195000,
    assessedValue: 142000,
    lastSalePrice: 89000,
    lastSaleDate: "2008-11-03",
    equityPercent: 45,
    mortgageBalance: 107000,
  },
  {
    id: "prop-004",
    address: "321 Elm Court",
    city: "Miami",
    state: "FL",
    zip: "33101",
    county: "Miami-Dade",
    ownerName: "Sarah Williams",
    score: 78,
    dataSource: "PropStream",
    outreachStatus: "contacted",
    lastContactDate: "2025-01-12",
    lastContactMethod: "email",
    sentiment: "neutral",
    nextFollowUpDate: "2025-01-30",
    phoneNumbers: "(305) 555-3456",
    emails: "swilliams@outlook.com",
    foreclosure: false,
    preForeclosure: false,
    taxDelinquent: true,
    vacant: false,
    createdAt: "2025-01-08",
    // Property details
    bedrooms: 2,
    bathrooms: 2,
    squareFeet: 1100,
    yearBuilt: 1982,
    lotSize: 0.12,
    propertyType: "Condo",
    estimatedValue: 265000,
    assessedValue: 198000,
    lastSalePrice: 145000,
    lastSaleDate: "2016-06-28",
    equityPercent: 62,
    mortgageBalance: 100000,
  },
  {
    id: "prop-005",
    address: "654 Cedar Lane",
    city: "Jacksonville",
    state: "FL",
    zip: "32210",
    county: "Duval",
    ownerName: "Michael Brown",
    score: 88,
    dataSource: "REapi",
    outreachStatus: "negotiating",
    lastContactDate: "2025-01-22",
    lastContactMethod: "call",
    sentiment: "hot",
    nextFollowUpDate: "2025-01-26",
    phoneNumbers: "(904) 555-7890, (904) 555-7891",
    emails: "mbrown@yahoo.com",
    foreclosure: false,
    preForeclosure: true,
    taxDelinquent: true,
    vacant: true,
    createdAt: "2025-01-02",
    // Property details
    bedrooms: 4,
    bathrooms: 2,
    squareFeet: 1850,
    yearBuilt: 1972,
    lotSize: 0.25,
    propertyType: "Single Family",
    estimatedValue: 310000,
    assessedValue: 225000,
    lastSalePrice: 165000,
    lastSaleDate: "2014-02-10",
    equityPercent: 55,
    mortgageBalance: 139000,
  },
  {
    id: "prop-006",
    address: "789 Birch Road",
    city: "St. Petersburg",
    state: "FL",
    zip: "33701",
    county: "Pinellas",
    ownerName: "Jennifer Davis",
    score: 45,
    dataSource: "BatchLeads",
    outreachStatus: "dnc",
    lastContactDate: "2025-01-10",
    lastContactMethod: "sms",
    sentiment: "cold",
    phoneNumbers: "(727) 555-2345",
    foreclosure: false,
    preForeclosure: false,
    taxDelinquent: false,
    vacant: false,
    createdAt: "2025-01-15",
    // Property details
    bedrooms: 3,
    bathrooms: 2,
    squareFeet: 1600,
    yearBuilt: 1988,
    lotSize: 0.19,
    propertyType: "Single Family",
    estimatedValue: 345000,
    assessedValue: 268000,
    lastSalePrice: 225000,
    lastSaleDate: "2019-04-15",
    equityPercent: 35,
    mortgageBalance: 224000,
  },
  {
    id: "prop-007",
    address: "456 Willow Way",
    city: "Fort Lauderdale",
    state: "FL",
    zip: "33301",
    county: "Broward",
    ownerName: "David Martinez",
    score: 71,
    dataSource: "ATTOM",
    outreachStatus: "new",
    phoneNumbers: "(954) 555-6789",
    emails: "dmartinez@gmail.com",
    foreclosure: false,
    preForeclosure: false,
    taxDelinquent: false,
    vacant: true,
    createdAt: "2025-01-20",
    // Property details
    bedrooms: 3,
    bathrooms: 2.5,
    squareFeet: 1750,
    yearBuilt: 1995,
    lotSize: 0.16,
    propertyType: "Townhouse",
    estimatedValue: 385000,
    assessedValue: 295000,
    lastSalePrice: 210000,
    lastSaleDate: "2017-09-05",
    equityPercent: 58,
    mortgageBalance: 162000,
  },
  {
    id: "prop-008",
    address: "123 Palm Circle",
    city: "Gainesville",
    state: "FL",
    zip: "32601",
    county: "Alachua",
    ownerName: "Lisa Anderson",
    score: 94,
    dataSource: "PropStream",
    outreachStatus: "hot",
    lastContactDate: "2025-01-23",
    lastContactMethod: "call",
    sentiment: "hot",
    nextFollowUpDate: "2025-01-27",
    phoneNumbers: "(352) 555-0123",
    emails: "landerson@email.com",
    contactNotes: "Very motivated seller, inherited property from parents. Wants quick close.",
    foreclosure: false,
    preForeclosure: false,
    taxDelinquent: true,
    vacant: true,
    createdAt: "2025-01-01",
    // Property details - inherited, free & clear
    bedrooms: 3,
    bathrooms: 2,
    squareFeet: 1380,
    yearBuilt: 1968,
    lotSize: 0.21,
    propertyType: "Single Family",
    estimatedValue: 225000,
    assessedValue: 165000,
    lastSalePrice: 45000,
    lastSaleDate: "1998-07-12",
    equityPercent: 100,
    mortgageBalance: 0,
  },
  {
    id: "prop-009",
    address: "987 Magnolia Street",
    city: "Tallahassee",
    state: "FL",
    zip: "32301",
    county: "Leon",
    ownerName: "James Wilson",
    score: 56,
    dataSource: "REapi",
    outreachStatus: "contacted",
    lastContactDate: "2025-01-14",
    lastContactMethod: "voicemail",
    sentiment: "neutral",
    nextFollowUpDate: "2025-02-01",
    phoneNumbers: "(850) 555-4567",
    foreclosure: true,
    preForeclosure: false,
    taxDelinquent: false,
    vacant: false,
    createdAt: "2025-01-12",
    // Property details
    bedrooms: 4,
    bathrooms: 2,
    squareFeet: 1950,
    yearBuilt: 1985,
    lotSize: 0.28,
    propertyType: "Single Family",
    estimatedValue: 275000,
    assessedValue: 205000,
    lastSalePrice: 185000,
    lastSaleDate: "2018-01-22",
    equityPercent: 25,
    mortgageBalance: 206000,
  },
  {
    id: "prop-010",
    address: "246 Cypress Boulevard",
    city: "Pensacola",
    state: "FL",
    zip: "32501",
    county: "Escambia",
    ownerName: "Emily Taylor",
    score: 82,
    dataSource: "BatchLeads",
    outreachStatus: "contacted",
    lastContactDate: "2025-01-19",
    lastContactMethod: "sms",
    sentiment: "warm",
    nextFollowUpDate: "2025-01-29",
    phoneNumbers: "(850) 555-8901",
    emails: "etaylor@hotmail.com",
    foreclosure: false,
    preForeclosure: true,
    taxDelinquent: false,
    vacant: false,
    createdAt: "2025-01-06",
    // Property details
    bedrooms: 3,
    bathrooms: 2,
    squareFeet: 1550,
    yearBuilt: 1975,
    lotSize: 0.20,
    propertyType: "Single Family",
    estimatedValue: 215000,
    assessedValue: 158000,
    lastSalePrice: 135000,
    lastSaleDate: "2013-11-08",
    equityPercent: 48,
    mortgageBalance: 112000,
  },
  {
    id: "prop-011",
    address: "753 Hibiscus Lane",
    city: "Naples",
    state: "FL",
    zip: "34102",
    county: "Collier",
    ownerName: "Thomas Moore",
    score: 63,
    dataSource: "ATTOM",
    outreachStatus: "new",
    phoneNumbers: "(239) 555-2468",
    foreclosure: false,
    preForeclosure: false,
    taxDelinquent: true,
    vacant: false,
    createdAt: "2025-01-21",
    // Property details - higher end market
    bedrooms: 4,
    bathrooms: 3,
    squareFeet: 2450,
    yearBuilt: 2002,
    lotSize: 0.32,
    propertyType: "Single Family",
    estimatedValue: 625000,
    assessedValue: 485000,
    lastSalePrice: 385000,
    lastSaleDate: "2015-05-18",
    equityPercent: 65,
    mortgageBalance: 219000,
  },
  {
    id: "prop-012",
    address: "159 Jasmine Court",
    city: "Sarasota",
    state: "FL",
    zip: "34236",
    county: "Sarasota",
    ownerName: "Patricia White",
    score: 76,
    dataSource: "PropStream",
    outreachStatus: "follow-up",
    lastContactDate: "2025-01-17",
    lastContactMethod: "email",
    sentiment: "warm",
    nextFollowUpDate: "2025-01-31",
    phoneNumbers: "(941) 555-1357",
    emails: "pwhite@aol.com",
    foreclosure: false,
    preForeclosure: false,
    taxDelinquent: false,
    vacant: true,
    createdAt: "2025-01-09",
    // Property details
    bedrooms: 2,
    bathrooms: 2,
    squareFeet: 1250,
    yearBuilt: 1992,
    lotSize: 0.14,
    propertyType: "Condo",
    estimatedValue: 295000,
    assessedValue: 225000,
    lastSalePrice: 178000,
    lastSaleDate: "2016-12-01",
    equityPercent: 70,
    mortgageBalance: 88000,
  },
  {
    id: "prop-013",
    address: "482 Sunrise Drive",
    city: "Clearwater",
    state: "FL",
    zip: "33755",
    county: "Pinellas",
    ownerName: "Kevin Thompson",
    score: 89,
    dataSource: "REapi",
    outreachStatus: "hot",
    lastContactDate: "2025-01-24",
    lastContactMethod: "call",
    sentiment: "hot",
    nextFollowUpDate: "2025-01-28",
    phoneNumbers: "(727) 555-3698",
    emails: "kthompson@gmail.com",
    foreclosure: false,
    preForeclosure: true,
    taxDelinquent: true,
    vacant: false,
    createdAt: "2025-01-03",
    // Property details
    bedrooms: 3,
    bathrooms: 2,
    squareFeet: 1425,
    yearBuilt: 1970,
    lotSize: 0.17,
    propertyType: "Single Family",
    estimatedValue: 285000,
    assessedValue: 212000,
    lastSalePrice: 152000,
    lastSaleDate: "2014-08-25",
    equityPercent: 52,
    mortgageBalance: 137000,
  },
  {
    id: "prop-014",
    address: "615 Bayview Terrace",
    city: "West Palm Beach",
    state: "FL",
    zip: "33401",
    county: "Palm Beach",
    ownerName: "Angela Harris",
    score: 72,
    dataSource: "BatchLeads",
    outreachStatus: "contacted",
    lastContactDate: "2025-01-16",
    lastContactMethod: "sms",
    sentiment: "warm",
    nextFollowUpDate: "2025-01-30",
    phoneNumbers: "(561) 555-7412",
    emails: "aharris@yahoo.com",
    foreclosure: false,
    preForeclosure: false,
    taxDelinquent: true,
    vacant: false,
    createdAt: "2025-01-11",
    // Property details
    bedrooms: 3,
    bathrooms: 2.5,
    squareFeet: 1680,
    yearBuilt: 1998,
    lotSize: 0.18,
    propertyType: "Single Family",
    estimatedValue: 425000,
    assessedValue: 328000,
    lastSalePrice: 265000,
    lastSaleDate: "2017-03-14",
    equityPercent: 45,
    mortgageBalance: 234000,
  },
  {
    id: "prop-015",
    address: "928 Oceanfront Boulevard",
    city: "Daytona Beach",
    state: "FL",
    zip: "32118",
    county: "Volusia",
    ownerName: "Richard Clark",
    score: 58,
    dataSource: "ATTOM",
    outreachStatus: "new",
    phoneNumbers: "(386) 555-9524",
    foreclosure: true,
    preForeclosure: false,
    taxDelinquent: false,
    vacant: true,
    createdAt: "2025-01-22",
    // Property details
    bedrooms: 2,
    bathrooms: 1,
    squareFeet: 950,
    yearBuilt: 1958,
    lotSize: 0.12,
    propertyType: "Single Family",
    estimatedValue: 175000,
    assessedValue: 128000,
    lastSalePrice: 95000,
    lastSaleDate: "2010-06-30",
    equityPercent: 38,
    mortgageBalance: 108000,
  },
  {
    id: "prop-016",
    address: "347 Lakeside Circle",
    city: "Ocala",
    state: "FL",
    zip: "34470",
    county: "Marion",
    ownerName: "Susan Lewis",
    score: 81,
    dataSource: "PropStream",
    outreachStatus: "negotiating",
    lastContactDate: "2025-01-25",
    lastContactMethod: "call",
    sentiment: "hot",
    nextFollowUpDate: "2025-01-29",
    phoneNumbers: "(352) 555-8463",
    emails: "slewis@outlook.com",
    contactNotes: "Ready to sell, needs 30 day close for relocation.",
    foreclosure: false,
    preForeclosure: false,
    taxDelinquent: false,
    vacant: false,
    createdAt: "2025-01-04",
    // Property details
    bedrooms: 4,
    bathrooms: 2.5,
    squareFeet: 2200,
    yearBuilt: 2005,
    lotSize: 0.35,
    propertyType: "Single Family",
    estimatedValue: 365000,
    assessedValue: 285000,
    lastSalePrice: 245000,
    lastSaleDate: "2018-09-12",
    equityPercent: 55,
    mortgageBalance: 164000,
  },
];
